### ISSUE TITLE
Adjust path styles (colors)

### ISSUE THREAD

**Issue by hellej** [DigitalGeographyLab/green-path-ui#6]
Colored path styles could be improved, but how? 

The current style is shown in the left screenshot - the right one has the same style but without the black line borders. If we want to go without the line borders, either colors of the edges or the background map need to be adjusted somehow.

<p align="middle">
<img src="https://user-images.githubusercontent.com/16876553/68242283-eb975500-0018-11ea-815c-01b1029ec440.png" width="40%">
<img src="https://user-images.githubusercontent.com/16876553/68242401-1aadc680-0019-11ea-9cc0-3a0b028f0c3e.png" width="40%">
</p>

In the screenshot below, the line borders are a bit thinner (perhaps this is sufficient for now):

<img src="https://user-images.githubusercontent.com/16876553/68247201-f7881480-0022-11ea-8a77-f858d713e0db.png" width="40%">
</p>

**Comment by hellej** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UI tweaks: adjust colored path style, add heading "HOPE" on upper left corner of the map](https://trello.com/c/xt6lpWYO/51-ui-tweaks-adjust-colored-path-style-add-heading-hope-on-upper-left-corner-of-the-map)

**Comment by hellej** [comment]
On a dark background the colors show clearly but the map itself doesn't look very pleasant...

<img src="https://user-images.githubusercontent.com/16876553/68244430-7d08c600-001d-11ea-9773-9a8a37dcdad1.png" width="40%">

**Comment by EWillberg** [comment]
I wouldn't remove the line borders or change the background color. But maybe the borders could be made thinner as you did in the third screenshot. Another possibility is to adjust the border color closer to grey so that the border doesn't take that much attention from red, yellow and green.

**Comment by apoom** [comment]
Hi Joose, thanks for providing these comparisons! I agree with Elias - thinner lines (and may be a bit more greyish) do for now really well. 
True, sustaining borders improves the contrast with the background map and allows to apply different colour schemes, incl. for colour-blindness.
If we want to provide a possibility for the user to choose black mode, then the showed solution looks really nice. It's like artwork and suitable for presentations to stress different route qualities (not directly guiding the user) :)

**Comment by hellej** [comment]
@EWillberg and @apoom, thanks for commenting these. As of d5595fe, the line borders are now thinner (and greyer). We can tweak the styles more later :) Also, the toggle between light and dark mode would be cool - we could add it to the backlog as a 'nice to have' feature.
